#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: Update chat archive

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  load:
    # load docs/ and state/ from this repo to pass along to update job
    name: Load state
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v6

      - uses: actions/upload-artifact@v6
        with:
          path: |
            docs
            state
          name: current-state

  update:
    name: Update archive
    needs: load
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'apache/fineract-chat-archive'

      - uses: actions/download-artifact@v7
        with:
          name: current-state

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Fetch messages
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNELS_ALLOWLIST: '#fineract'
          LOOKBACK_DAYS: 1
        run: ./gradlew --quiet updateChatArchive

      - uses: actions/upload-artifact@v6
        with:
          path: |
            docs
            state
          name: new-state

  save:
    # commit any changes to docs/ and state/
    name: Save state
    needs: update
    runs-on: ubuntu-slim
    timeout-minutes: 1
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          name: new-state

      - name: Commit updates
        run: |
          if [ -d docs ]; then
            git add docs
          fi
          if [ -d state ]; then
            git add state
          fi
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update chat archive"
          git push
